import cv2
#BGR image
print("BGR image")
img=cv2.imread("F:\\5.Python\\Tutorial\\standard_test_images\\4.1.01.tiff")
print("Img Data Type: ",end="")
print(type(img))
print("Img DType: ",end="")
print(img.dtype)
print("Img Shape:",end="")
print(img.shape)
print("Img Dimension:",end="")
print(img.ndim)
print("Img Size: ",end="")
print(img.size)

#Greyscale image
print()
print("Greyscale image")
img=cv2.imread("F:\\5.Python\\Tutorial\\standard_test_images\\4.1.01.tiff",0)
print("Img Data Type: ",end="")
print(type(img))
print("Img DType: ",end="")
print(img.dtype)
print("Img Shape:",end="")
print(img.shape)
print("Img Dimension:",end="")
print(img.ndim)
print("Img Size: ",end="")
print(img.size)